name: Histeria
version: ${project.version}
main: fr.zelytra.histeria.Histeria
api-version: 1.16
authors: [ Zelytra ]
description: Histeria server core
website: http://zelytra.fr

commands:
  server:
    description: Open server selector interface

  hgive:
    description: Give custom item
