name: Histeria
version: 2.0
main: fr.zelytra.histeria.Histeria
depend:
  - WorldEdit
api-version: 1.16
authors: [ Zelytra ]
description: Histeria server core
website: http://zelytra.fr

commands:
  test:
    description: a test command
    permission: histeria.test

  server:
    description: Open server selector interface
    permission: histeria.server

  hgive:
    description: Give custom item
    permission: histeria.hgive

  wiki:
    description: Acces to wiki page
    permission: histeria.hgive
