name: Histeria
version: 3.0
main: fr.zelytra.histeria.Histeria
depend:
  - WorldEdit
  - LuckPerms
softdepend:
  - Factions
api-version: 1.18
authors: [ Zelytra ]
description: Histeria server core
website: https://zelytra.fr

commands:
  test:
    description: a test command
    permission: histeria.test

  ping:
    description: Return the ping of the player
    permission: histeria.ping

  server:
    description: Open server selector interface
    permission: histeria.server

  hgive:
    description: Give custom item
    permission: histeria.hgive

  wiki:
    description: Acces to wiki page
    permission: histeria.wiki

  hguard:
    description: all hguard command
    permission: histeria.hguard

  speed:
    description: Change player fly speed
    permission: histeria.speed

  nightvision:
    description: Give/Remove nightvision to the player
    permission: histeria.nightvision
    aliases:
      - nv
      - night

  feed:
    description: Feed a player
    permission: histeria.feed

  enderchest:
    description: Open the player enderchest
    permission: histeria.enderchest
    aliases:
      - ec
      - enderc
      - echest

  craft:
    description: Open a crafting inventory
    permission: histeria.craft

  heal:
    description: Heal a player
    permission: histeria.heal

  hat:
    description: Set any item on player head
    permission: histeria.hat

  fly:
    description: Allow a player to fly
    permission: histeria.fly

  xpbottle:
    description: Convert player experienc into experience orb
    permission: histeria.xpbottle

  gmc:
    description: Change player gamemode to creative
    permission: histeria.gamemode

  gms:
    description: Change player gamemode to survival
    permission: histeria.gamemode

  gmsc:
    description: Change player gamemode to spectator
    permission: histeria.gamemode

  stats:
    description: Show statistic of a player
    permission: histeria.stats
    aliases:
      - stat
      - statistic

  bank:
    description: Bank commands
    permission: histeria.bank

  emote:
    description: Show all emote
    permission: histeria.emote

  bug:
    description: Show discord link to report a bug or a problem
    permission: histeria.bug
    aliases:
      - problem
      - report

  social:
    description: Show all social link of the server
    permission: histeria.social
    aliases:
      - discord
      - website
      - web
      - link

  freeze:
    description: To freeze a player
    permission: histeria.freeze

  unfreeze:
    description: To unfreeze a player
    permission: histeria.freeze

  lang:
    description: change lang of a player
    permission: histeria.lang

  compress:
    description: Compress all your cobble blocks
    permission: histeria.compress

  near:
    description: Display nearest player
    permission: histeria.near

  slot:
    description: Change slot number of the current server
    permission: histeria.slot

  broadcast:
    description: Broadcast messages
    permission: histeria.broadcast
    aliases:
      - bc

  inventorysee:
    description: Look and modify the inventory of another player
    permission: histeria.inventorysee
    aliases:
      - invsee

  hkick:
    description: Kick a player with a reason message
    permission: histeria.hkick

  spawn:
    description: Teleport the layer to spawn of the server
    permission: histeria.spawn

  setspawn:
    description: Set the world spawn of the server
    permission: histeria.setspawn

  mute:
    description: Mute a player
    permission: histeria.mute

  unmute:
    description: Unmute a player
    permission: histeria.mute

  hban:
    description: Ban a player
    permission: histeria.ban

  unban:
    description: Unban a player
    permission: histeria.ban

  shop:
    description: Open shop page
    permission: histeria.shop

  stand:
    description: Stand
    permission: histeria.stand

  afk:
    description: Show player afk time
    permission : histeria.afk

  vanish:
    description: Vanish player on the server
    permission: histeria.vanish

  unvanish:
    description: Unvanish player on the server
    permission: histeria.vanish

  randomtp:
    description: Teleport the player in a random place of the world
    permission: histeria.randomtp
    aliases:
      - rtp

  tpa:
    description: Teleport a player to another player
    permission: histeria.tpa

  tpaccept:
    description: Accept the teleportation of player to an other
    permission: histeria.tpa

  tpdeny:
    description: Deny the teleportation of player to an other
    permission: histeria.tpa

  clearlag:
    description: Run clearlag execution
    permission: histeria.clearlag

  kit:
    description: Open kit menu
    permission: histeria.kit

  vote:
    description: Show vote link
    permission: histeria.vote

  forcevote:
    description: Force vote a player
    permission: histeria.forcevote

  switchserver:
    description: Switch player(s) to other server
    permission: histeria.switchserver

  home:
    description: Teleport to the home
    permission: histeria.home

  delhome:
    description: Remove a home
    permission: histeria.home

  sethome:
    description: Set a home
    permission: histeria.home

  listhome:
    description: Show home list
    permission: histeria.home

  adminhome:
    description: Show all player home
    permission: histeria.adminhome

  adminbank:
    description: Change player bank account
    permission: histeria.adminbank

  npc:
    description: NPC command
    permission: histeria.npc

  arenachest:
    description: ArenaChest command
    permission: histeria.arenachest
    aliases:
      - ac

  topstats:
    description: Display top stats of player by criteria
    permission: histeria.topstats

  hologram:
    description: Hologram command
    permission: histeria.hologram

  harddelete:
    description: Hard delete inventorys of a player with synch server
    permission: histeria.harddelete
    aliases:
      - hd

  admin:
    description: Change player status between player and admin
    permission: histeria.admin

  job:
    description: Open job detail menu
    permission: histeria.job

  blackmarket:
    description: Access to the blackmarket or send an item to them
    permission: histeria.blackmarket
    aliases:
      - bm

  henchant:
    description: Add custom enchant to an item
    permission: histeria.henchant
