name: Histeria
version: 2.0
main: fr.zelytra.histeria.Histeria
depend:
  - WorldEdit
  - LuckPerms
api-version: 1.16
authors: [ Zelytra ]
description: Histeria server core
website: https://zelytra.fr

commands:
  test:
    description: a test command
    permission: histeria.test

  server:
    description: Open server selector interface
    permission: histeria.server

  hgive:
    description: Give custom item
    permission: histeria.hgive

  wiki:
    description: Acces to wiki page
    permission: histeria.wiki

  hguard:
    description: all hguard command
    permission: histeria.hguard

  speed:
    description: Change player fly speed
    permission: histeria.speed

  nightvision:
    description: Give/Remove nightvision to the player
    permission: histeria.nightvision
    aliases:
      - nv
      - night

  feed:
    description: Feed a player
    permission: histeria.feed

  enderchest:
    description: Open the player enderchest
    permission: histeria.enderchest
    aliases:
      - ec
      - enderc
      - echest

  ping:
    description: Get player ping
    permission: histeria.ping

  craft:
    description: Open a crafting inventory
    permission: histeria.craft

  heal:
    description: Heal a player
    permission: histeria.heal

  hat:
    description: Set any item on player head
    permission: histeria.hat

  fly:
    description: Allow a player to fly
    permission: histeria.fly

  xpbottle:
    description: Convert player experienc into experience orb
    permission: histeria.xpbottle

  gmc:
    description: Change player gamemode to creative
    permission: histeria.gamemode

  gms:
    description: Change player gamemode to survival
    permission: histeria.gamemode

  gmsc:
    description: Change player gamemode to spectator
    permission: histeria.gamemode

  stats:
    description: Show statistic of a player
    permission: histeria.stats
    aliases:
      - stat
      - statistic

  bank:
    description: Bank commands
    permission: histeria.bank

  emote:
    description: Show all emote
    permission: histeria.emote

  bug:
    description: Show discord link to report a bug or a problem
    permission: histeria.bug
    aliases:
      - problem
      - report

  social:
    description: Show all social link of the server
    permission: histeria.social
    aliases:
      - discord
      - website
      - web
      - link

  freeze:
    description: To freeze a player
    permission: histeria.freeze

  unfreeze:
    description: To unfreeze a player
    permission: histeria.freeze

  lang:
    description: change lang of a player
    permission: histeria.lang

  compress:
    description: Compress all your cobble blocks
    permission: histeria.compress

  near:
    description: Display nearest player
    permission: histeria.near

  slot:
    description: Change slot number of the current server
    permission: histeria.slot

  broadcast:
    description: Broadcast messages
    permission: histeria.broadcast
    aliases:
      - bc

  inventorysee:
    description: Look and modify the inventory of another player
    permission: histeria.inventorysee
    aliases:
      - invsee

  hkick:
    description: Kick a player with a reason message
    permission: histeria.hkick

  spawn:
    description: Teleport the layer to spawn of the server
    permission: histeria.spawn

  setspawn:
    description: Set the world spawn of the server
    permission: histeria.setspawn

  mute:
    description: Mute a player
    permission: histeria.mute

  hban:
    description: Ban a player
    permission: histeria.ban

  unban:
    description: Unban a player
    permission: histeria.ban

  shop:
    description: Open shop page
    permission: histeria.shop

  stand:
    description: Stand
    permission: histeria.stand

